### ISSUE TITLE
Why are commented functions on top of uncommented?

### ISSUE THREAD

**Issue by AllNamesRTaken** [DrMueller/TS-Arrange2#4]
This feels very deliberate but at the same time strange. Why is my commented private function landing above a public uncommented?

Is this a bug?

**Comment by DrMueller** [comment]
It seems like 

```typescript
const children = classBodyNode.getChildren();
```

Doesn't return commented code, therefore it isn't processed. That said, I don't think we can also make commented code work.

**Comment by dustincleveland** [comment]
It sounds like sorting commented members isn't something easily supported by the APIs you're using. That's unfortunate.

Our team has adopted a convention of alphabetizing our classes, of which we have _many_, and most of which are very unorganized. There's also a need to add member documentation in many places as the project domain is quite complex. Adding documentation, it seems, would in large part invalidate this extension's benefits.

I point this out just to illustrate how valuable this extension can be, and how easily that value can be diminished if comments prevent proper member sorting.

Perhaps some updates have been made to the API, or maybe some other solution would be possible, albeit more involved?

**Comment by DrMueller** [comment]
@dustincleveland Thank you for the feedback. As the compiler API is also making a lot of progress, probably we find something or I check with the devs directly.

**Comment by DrMueller** [comment]
@AllNamesRTaken @dustincleveland As you might have read in the announcement, I'm currently thinking about a rewrite away from string parsing to the use of the TS API. Do you have some inputs or ideas, which would enhance the extension other than the comments issue?

**Comment by dustincleveland** [comment]
It would definitely be great if getters and setters could be kept together, and if there were configuration rules to specify where properties should be placed.

Also, although there are other extensions to sort import statements, it'd be awesome to have a single extension/command to apply all of the sorting rules you need. 

It may also be desirable to have the ability to sort top-level code structures, like interfaces, classes, types, and so on.

Glad to hear you're considering some updates! That would be awesome. Thanks, and I'll let you know if I have any other ideas.

**Comment by DrMueller** [comment]
@dustincleveland Thank you for the feedback. Regarding the import statements: VSCode itself (or the TSLint extension) already does that pretty well and also considers the TSLint rules. Just add the following  config in the settings

```
    "editor.codeActionsOnSave": {
        "source.fixAll.tslint": true
    }
```

This fixes all import errors on save, which is pretty neat.

**Comment by DrMueller** [comment]
To be fair, I have quite a hard time justifying a rework: The new alphabetize option does more or less the same as my extension and allows a easier usage thanks to "codeActionsOnSave":

```
    "member-ordering": [
      true,
      {
        "order": [
          "public-static-field",
          "protected-static-field",
          "private-static-field",
          "public-instance-field",
          "protected-instance-field",
          "private-instance-field",
          "public-constructor",
          "protected-constructor",
          "private-constructor",
          "public-static-method",
          "protected-static-method",
          "private-static-method",
          "public-instance-method",
          "protected-instance-method",
          "private-instance-method"
        ],
        "alphabetize": true
      }
    ],
```

Also, TSLint is currently migrating to ESLint, which will change quite a lot I'd guess.
